apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-proxy.fullname" . }}-config
  labels:
    {{- include "mcp-proxy.labels" . | nindent 4 }}
data:
  proxy.toml: |
    {{- .Values.config | nindent 4 }}
